### ISSUE TITLE
testing error for k>2, such as k=3

### ISSUE THREAD

**Issue by ankblue** [Xing-CHEN18/NeuralODEs_for_physics#1]
parser.add_argument('--steps', type=int, default=3, metavar = 'k', help='the number of shifted steps(new dimensions k)')

after training the neural ode using steps =3 and while testing getting below error

RuntimeError: Error(s) in loading state_dict for ODEFunc:
	size mismatch for ext0.0.weight: copying a param with shape torch.Size([200, 6]) from checkpoint, the shape in current model is torch.Size([200, 5]).
	size mismatch for ext0.6.weight: copying a param with shape torch.Size([3, 200]) from checkpoint, the shape in current model is torch.Size([2, 200]).
	size mismatch for ext0.6.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).

how can solve this error?

**Comment by Xing-CHEN18** [comment]
When you load the model, the 'dim' parameter in the model ODEFunc should also be set as 3, 
hope it helps!

**Comment by ankblue** [comment]
Thanks, it helped.
